version: "3.8"

services:
  client:
    build: ./frontend
    container_name: client_c
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules

  api:
    build: ./backend
    container_name: api_c
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb


  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  